name: Upload thing when pushing something (Stable TCPD Trials)

on:
  push:
    tags:
      - "TCPD-*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Set up JDK environment to 8
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 17

      # 1
      - name: Checkout code
        uses: actions/checkout@v2

      # 2
      - name: Build
        run: make build
      
      # 3
      - name: Sign APK
        run: make sign-release-apk
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      
      # 4
      - name: Move binaries
        run: make move-binaries

      # 5
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
              build/*.apk
              build/*.jar

